### PR TITLE
Working prototype

### PR DESCRIPTION
**Pull request by glesage**
Separated the email & SMS to separate files
The following now work:
- Send resume to email(s) & to sms
- Send resume to email(s)
- Send resume to phone

This does still have your resume & site hard coded

### CODE REVIEW

**Comment by MrMaksimize** [comment]
Hey Geoff I took #7 but this one is unmergeable :(

**Comment by glesage** [comment]
Doesn't matter that its unmergeableactually now? Cus this is just a previous version of it...

**Comment by glesage** [comment]
Hey, so remind me about how I'm supposed to do branches, changes & pull
requests again?
So far I've just forked your repo and worked on Dev, and whenever I have a
stable version I did a pull request... to dev

On Tue, Oct 1, 2013 at 12:18 PM, Maksim Pecherskiy <notifications@github.com

**Comment by MrMaksimize** [comment]
Cool -- yeah I'll tell ya tomorrow.  The main idea is that the pull request is updated automatically as the branch gets updated.

**Pull request closed without merging**
